### ISSUE TITLE
Chatroom: prevent overusage of newlines

### ISSUE THREAD

**Issue by CasperKjaerhus** [Deaxz/p3#13]
![image](https://user-images.githubusercontent.com/56830573/97425698-bca57d80-1912-11eb-96f7-c0c2b253e1d6.png)

Please prevent this

**Comment by Deaxz** [comment]
Idiot description

**Comment by Deaxz** [comment]
Fixed.
https://github.com/Deaxz/p3/commit/2894003e887321aab07745d68be97e845b11606b
